### ISSUE TITLE
add a "characters required" option to the generated password

### ISSUE THREAD

**Issue by ibaaj** [Bramas/pure-password-manager#1]
This password manager seems very promising 

However some websites ask you to put non alphanumeric character or to use a forced length for the password

As it can be useful to add this field to generate a new password, I think that it can be also cool to keep these options into a small volatile database (like localstorage or anything else) 

I'm not sure to have the right solution, but we can start think about to improve this program 

long live PPM

**Comment by Bramas** [comment]
thanks for the feedback!
you're absolutly right. I think I should add a field for the password format like keepass does if I remember well.

keeping the format associated with each website in the local storage is also a good idea but i think we can go even further and maybe create a database of all the format at least for all wellknown website that have wierd restriction so that we can pre-fill the field. but maybe thats too complex. another possibility is to propose only 3 or 4 possible formats like only numeric, alphanumeric, or complex and a slider for the length limitation if any.
so that it is really fast to select the format and there is no need to save it.
The last problem is that password restriction is clearly mentionned during the registration process but dont during the login so it is easy to forget what is the restriction of each website.

**Comment by Bramas** [comment]
Solved with last version (format saved in Ethereum blockchain)
